[workspace] 
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies] 
pirate = { path = "." }

[tasks] 

[package] 
name = "pirate"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "0.*" }

[package.host-dependencies] 
hatchling = "==1.26.3"